[window]
padding = { x = 5, y = 5 }
opacity = 1.0

[font]
normal = { family = "Reddit Mono", style = "Regular" }
size = 12

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.bright]
black = "#555555"
red = "#FF5555"
green = "#55FF55"
yellow = "#FFFF55"
blue = "#5555FF"
magenta = "#FF55FF"
cyan = "#55FFFF"
white = "#FFFFFF"

[colors.normal]
black = "#000000"
red = "#AA0000"
green = "#00AA00"
yellow = "#AA5500"
blue = "#0000AA"
magenta = "#AA00AA"
cyan = "#00AAAA"
white = "#AAAAAA"

[cursor]
style = "Underline"
